name: video_downloader
description: A plugin for creating and managing download tasks. Supports iOS and Android.
version: 0.0.1
homepage: https://github.com/jargalbat/video_downloader
maintainer: Jargalbat J (@jargalbat)

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
#  provider: ^6.0.3
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.video_downloader
        pluginClass: VideoDownloaderPlugin
      ios:
        pluginClass: VideoDownloaderPlugin